In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [28]:
# Set random seed for reproducibility
np.random.seed(71025)

# Parameters
n_participants = 100
amount = 100  # $100
delays = [0, 7, 30, 90, 180, 365, 730]  # delays in days

# Generate random parameters for each participant
k_values = np.random.uniform(2, 4, n_participants)  # discounting rate
s_values = np.random.uniform(0.08, 0.1, n_participants)  # sensitivity parameter

# Create empty list to store all data
all_data = []

# Generate indifference points for each participant
for participant in range(n_participants):
    k = k_values[participant]
    s = s_values[participant]
    
    # Calculate indifference points using hyperboloid equation
    indifference_points = []
    for delay in delays:
        # V = A / ((1 + kD)^s)
        value = amount / ((1 + k * delay) ** s)
        value += np.random.normal(-10, 10)
        indifference_points.append(value)
    
    # Store data for this participant
    for i, delay in enumerate(delays):
        all_data.append({
            'participant_id': participant + 1,
            'k': k,
            's': s,
            'delay': delay,
            'indifference_point': indifference_points[i]
        })

# Convert to DataFrame
df = pd.DataFrame(all_data)

participant_df = df.pivot(index='participant_id', columns='delay', values='indifference_point').reset_index()
participant_df.columns = ['participant_id', 'delay_0', 'delay_7', 'delay_30', 'delay_90', 'delay_180', 'delay_365', 'delay_730']
participant_df['Amount'] = amount
participant_df['Commodity'] = 'Money Loss'
participant_df

,participant_id,delay_0,delay_7,delay_30,delay_90,delay_180,delay_365,delay_730,Amount,Commodity
0,1,87.046932,80.078204,68.221727,46.478879,55.379051,47.279112,34.295639,100,Money Loss
1,2,89.177107,71.726304,43.333467,65.690332,63.629643,45.155384,47.916840,100,Money Loss
2,3,91.276222,77.409747,64.391917,52.485518,26.983355,62.649402,43.557919,100,Money Loss
3,4,91.486833,84.930762,55.666893,64.308667,52.157362,42.989734,41.511777,100,Money Loss
4,5,77.974339,64.622040,57.850749,31.329557,49.864547,35.183108,37.665184,100,Money Loss
...,...,...,...,...,...,...,...,...,...,...
95,96,85.442298,65.317089,65.453550,40.894811,44.584631,52.212222,48.793758,100,Money Loss
96,97,115.893483,76.552757,51.912755,45.983869,51.292767,57.769858,29.562199,100,Money Loss
97,98,77.935952,59.918356,60.380324,64.621485,40.058665,56.056265,51.186185,100,Money Loss
98,99,77.036585,61.518476,57.402661,61.050430,51.040938,65.831342,41.575091,100,Money Loss
99,100,94.759086,81.746241,60.719372,54.537328,62.513515,57.969551,46.176207,100,Money Loss

In [29]:
disc_params = df[['participant_id', 'k', 's']].drop_duplicates().reset_index(drop=True)
disc_params['Amount'] = amount
disc_params['Commodity'] = 'Money Loss'
disc_params

    participant_id         k         s  Amount   Commodity
0                1  2.034099  0.083537     100  Money Loss
1                2  2.427686  0.099411     100  Money Loss
2                3  3.254464  0.091251     100  Money Loss
3                4  2.807573  0.089038     100  Money Loss
4                5  2.933205  0.093733     100  Money Loss
..             ...       ...       ...     ...         ...
95              96  2.089354  0.082558     100  Money Loss
96              97  3.445598  0.094931     100  Money Loss
97              98  2.653300  0.082232     100  Money Loss
98              99  2.523452  0.085444     100  Money Loss
99             100  2.138150  0.081585     100  Money Loss

[100 rows x 5 columns]

In [30]:
save_part = pd.concat([save_part, participant_df], axis=0)
save_params = pd.concat([save_params, disc_params], axis=0)

In [31]:
save_part

,participant_id,delay_0,delay_7,delay_30,delay_90,delay_180,delay_365,delay_730,Amount,Commodity
0,1,87.046932,84.277111,72.243497,50.209743,58.914898,50.619347,37.451249,100,Money
1,2,89.177107,75.492644,46.802605,68.841691,66.580923,47.911008,50.491086,100,Money
2,3,91.276222,79.830504,66.604739,54.505233,28.883542,64.432913,45.233046,100,Money
3,4,91.486833,87.797679,58.318142,66.738804,54.448234,45.143805,43.538278,100,Money
4,5,77.974339,67.437531,60.430258,33.680505,52.073265,37.252905,39.606010,100,Money
...,...,...,...,...,...,...,...,...,...,...
95,96,85.442298,65.317089,65.453550,40.894811,44.584631,52.212222,48.793758,100,Money Loss
96,97,115.893483,76.552757,51.912755,45.983869,51.292767,57.769858,29.562199,100,Money Loss
97,98,77.935952,59.918356,60.380324,64.621485,40.058665,56.056265,51.186185,100,Money Loss
98,99,77.036585,61.518476,57.402661,61.050430,51.040938,65.831342,41.575091,100,Money Loss
99,100,94.759086,81.746241,60.719372,54.537328,62.513515,57.969551,46.176207,100,Money Loss

In [32]:
save_params

    participant_id         k         s  Amount   Commodity
0                1  1.034099  0.083537     100       Money
1                2  1.427686  0.099411     100       Money
2                3  2.254464  0.091251     100       Money
3                4  1.807573  0.089038     100       Money
4                5  1.933205  0.093733     100       Money
..             ...       ...       ...     ...         ...
95              96  2.089354  0.082558     100  Money Loss
96              97  3.445598  0.094931     100  Money Loss
97              98  2.653300  0.082232     100  Money Loss
98              99  2.523452  0.085444     100  Money Loss
99             100  2.138150  0.081585     100  Money Loss

[400 rows x 5 columns]

In [35]:
save_part.to_csv("participant_data.csv", index=False)
save_params.to_csv("params_data.csv", index=False)